---
include:
  - board: xiao_ble//zmk
    shield: eyelash_sofle_prospector_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_sofle_prospector_dongle
  - board: nice_nano//zmk
    shield: eyelash_sofle_prospector_dongle prospector_adapter prospector_nice_nano
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_sofle_prospector_dongle_nice_nano
  - board: nice_nano//zmk
    shield: eyelash_sofle_peripheral_left nice_view
    artifact-name: eyelash_sofle_peripheral_left_nice_view
  - board: nice_nano//zmk
    shield: eyelash_sofle_peripheral_right nice_view
    artifact-name: eyelash_sofle_peripheral_right_nice_view
  - board: nice_nano//zmk
    shield: settings_reset
    artifact-name: settings_reset_nice_nano
  - board: xiao_ble//zmk
    shield: settings_reset
    artifact-name: settings_reset_xiao_ble
